[project]
name = "order-management-facility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.2",
    "fastapi>=0.128.0",
    "psycopg-binary>=3.3.2",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.45",
]
